### PR TITLE
estimation_methods_Fall17.py: switch to new MC's with fixed pu

### PR DESCRIPTION
**Pull request by ArturAkh**
All changes needed in `estimation_methods_Fall17.py` implemented in order to use the ntuples & newer MC samples. Few further ur: changed TTbar cross-section to the value on the Twiki.

I'll revert also the hotfix for recoil, since the ntuples should now contain the corresponding systematic shifts.

Cheers,

Artur

### CODE REVIEW

**Comment by ArturAkh** [comment]
Ok recoil hotfix is reverted now

**Comment by ArturAkh** [comment]
@swozniewski @stwunsch:

Is this used in your current setup? (So the right files for estimation methods?)

Cheers,

Artur

**Comment by ArturAkh** [comment]
Ok seems to be the case:

https://github.com/KIT-CMS/shape-producer/commit/6a21f75160005eecbc0b117ac99d8edef438569b#diff-2ecd1bb499e463b6ca8f745b0ea9d2f0

So this pull request can be closed I suppose?

**Comment by harrypuuter** [comment]
i guess this is dead now ?

**Pull request closed without merging**
